apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app1
  namespace: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      imagepullsecrets:
        - name: dockerhub-secret
      containers:
        - name: app1 
          image: balajik08/test_app1_argocd:v1.0.0
          ports:
            containerPort: 5000